### ISSUE TITLE
let op punten voor online images

### ISSUE THREAD

**Issue by Tolga1999** [DikkeTimo/Lamsa-page#2]
https://github.com/DikkeTimo/the-startup-responsive-interactieve-website/blob/7f1b99b3eb85af432ced5c517bead7689b3f9e46/index.html#L33-L34

![image](https://user-images.githubusercontent.com/112855878/212285396-f204923f-b727-4d2d-8132-80129315346d.png)

Zo moet het:
` <img id="creampot" src="./assets/cream.1.png" alt="picture cream pot" />`

**Comment by TimOosterveer** [comment]
Bedankt, het is gefixt!
