### ISSUE TITLE
Geschreven taal textarea

### ISSUE THREAD

**Issue by WesleySchorel** [DikkeTimo/Lamsa-page#9]
https://github.com/DikkeTimo/the-startup-responsive-interactieve-website/blob/d9f767142fe28cd4714d6c593fb3d514e0804231/index.html#L68-L75

De taal in de textarea is geschreven in het Nederlands, maar de rest van de website is geschreven in het Engels.  De html lang staat op "en".

**Comment by TimOosterveer** [comment]
Thanks, is gefixt!
